myapp/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'myapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('Beranda', views.index, name='index'),
    path('Dokumentasi', views.dokumentasi, name='dokumentasi'),
    path('Pengajuan', views.pengajuan, name='pengajuan'),
    path('Pengajuan/item/<int:item_id>', views.item, name='item'),
    path('Pengumuman', views.pengumuman, name='pengumuman'),
    path('Hubungi', views.contact, name='contact'),
    path('Dashboard', views.menu, name='menu'),

    url(r'^upload-doc/$', views.up_dokumentasi, name='upload_doc'),
    url(r'^upload-prop/$', views.up_proposal, name='upload_prop'),
    url(r'^upload-umum/$', views.up_pengumuman, name='upload_umum'),

    url(r'^login/$',views.user_login,name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [    
    path('', include('myapp.urls')),    
    path('admin/', admin.site.urls),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT) 
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

myapp/models.py
from djongo import models

# Create your models here.
class Dokumentasi(models.Model):    
    picture = models.FileField(upload_to='pic/', blank=True, default="dokumentasi_pic/dummy.jpg")
    
    class Meta:
        abstract = True

class Proposal(models.Model):
    file = models.FileField(upload_to='pic/')
    filename = models.CharField(max_length=500)    
    description = models.CharField(max_length=10000)
    
    class Meta:
        abstract = True

class Pengumuman(models.Model):
    nama = models.CharField(max_length=200) 
    tanggal = models.CharField(max_length=100)
    desc = models.CharField(max_length=1000)
    
    class Meta:
        abstract = True

class EntryDoc(models.Model):
    doc = models.EmbeddedField(
        model_container=Dokumentasi,              
    )    
class EntryProp(models.Model):
    prop = models.EmbeddedField(
        model_container=Proposal
    )
class EntryUm(models.Model):
    umum = models.EmbeddedField(
        model_container=Pengumuman
    )
   

myapp/views.py
from django.shortcuts import render, redirect
from django.core.mail import send_mail
from django.conf import settings
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.core.files.storage import FileSystemStorage
from django.core.paginator import Paginator

from myapp.models import EntryDoc, EntryProp, EntryUm
# from myapp.models import Dokumentasi, EntryDoc, EntryUm, Pengumuman

# Create your views here.
def index(request):
    context = {
        'page': 'Beranda',   
        'success': False,
        }    
    data = EntryDoc.objects.all()[:6]
    context['data'] = data 
    if request.method == 'POST':
        nama = request.POST['nama']
        nohp = request.POST['nohp']
        useremail = request.POST['email']
        subject = request.POST['jenis']
        message = request.POST['pesan'] + "\n identitas: \n" + "Nama: " + nama + ", No. HP: " + nohp
        email_from = useremail
        recipient_list = [settings.DEFAULT_EMAIL_RECEIVER,]
        send_mail( subject, message, email_from, recipient_list )
        context['success'] = True        
        return render(request, 'myapp/beranda.html', context)

    return render(request, 'myapp/beranda.html', context)

def dokumentasi(request):
    context = {
        'page': 'Dokumentasi',        
        }    
    data = EntryDoc.objects.all()    
    # for eachdata in data:
    #     print(eachdata.doc['picture'].url)
    #     print(type(eachdata.doc))        
    # context['data'] = data  
    paginator = Paginator(data, 3) # Show 3 contacts per page.

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context['page_obj'] = page_obj      
    return render(request, 'myapp/dokumentasi.html', context)

def pengajuan(request):
    context = {
        'page': 'Pengajuan',        
        }    
    data = EntryProp.objects.all()    
    # for eachdata in data:
    #     print(eachdata.id)
    #     print(type(eachdata))       
    # context['data'] = data
    paginator = Paginator(data, 3) # Show 3 contacts per page.

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context['page_obj'] = page_obj
    return render(request, 'myapp/pengajuan.html', context)

def item(request, item_id):
    context = {
        'page': 'Proposal',        
        }    
    data = EntryProp.objects.get(id=item_id)    
    context['data'] = data.prop
    return render(request, 'myapp/item.html', context)

def pengumuman(request):
    context = {
        'page': 'Pengumuman',        
        }    
    data = EntryUm.objects.all()

    # context['data'] = data
    paginator = Paginator(data, 3) # Show 3 contacts per page.

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context['page_obj'] = page_obj
    return render(request, 'myapp/pengumuman.html', context)

def contact(request):
    context = {
        'page': 'Hubungi',        
        }    
    return render(request, 'myapp/contact.html', context)

@login_required
def menu(request):
    context = {
        'page': 'Dashboard',       
        }    
    # form = DocumentForm()
    # context['form'] = form
    return render(request, 'myapp/admin-menu.html', context)

# auth
def user_login(request):
    if request.method == 'POST':
        context = {
        'page': 'Login',        
        } 
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return redirect('myapp:menu')
            else:
                context['error'] = 'Your Account was Unactive'
                return render(request, 'myapp/beranda.html', context)
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            context['error'] = "Username/Password Incorrect"
            return render(request, 'myapp/beranda.html', context)        
    else:        
        return render(request, 'myapp/beranda.html', context)

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('myapp:index'))

@login_required
def up_dokumentasi(request):
    if request.method == 'POST' and request.FILES:
        pic = request.FILES['picture']  
        fs = FileSystemStorage()
        filename = fs.save(pic.name, pic)
        uploaded_file_url = fs.url(filename)              
        db = EntryDoc()                            
        db.doc = {
            'picture':request.FILES['picture']
            }
        db.save()     
        print(uploaded_file_url)                
        return redirect('myapp:dokumentasi')
    return redirect('myapp:menu')

@login_required
def up_proposal(request):
    if request.method == 'POST' and request.FILES:
        berkas = request.FILES['berkas'] 
        judul = request.POST['judul'] 
        desc = request.POST['keterangan']
        fs = FileSystemStorage()
        filename = fs.save(berkas.name, berkas)
        uploaded_file_url = fs.url(filename)              
        db = EntryProp()                            
        db.prop = {
            'file':berkas,
            'filename':judul,
            'description':desc
            }
        db.save()     
        print(uploaded_file_url)                
        return redirect('myapp:pengajuan')
    return redirect('myapp:menu')

@login_required
def up_pengumuman(request):
    if request.method == 'POST':   
        nama = request.POST['namaMasjid'] 
        tgl = request.POST['tgl'] 
        desc = request.POST['masjidketerangan']                 
        db = EntryUm()                            
        db.umum = {
            'nama':nama,
            'tanggal':tgl,
            'desc':desc
            }
        db.save()                          
        return redirect('myapp:pengumuman')
    return redirect('myapp:menu')

myapp/templates/myapp/admin-menu.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{{page}}
{% endblock title %}

{% block header %}
<div class="header">
    H I B A H &nbsp;M A S J I D
</div>
{% endblock header %}

{% block content %}
<section class="beranda row">
    <div class="col">
        <h1 class="title p-2">Admin</h1>
        <div class="row">
            <button class="btn-second" id="modalDoc-btn">Upload Dokumentasi</button>
        </div>
        <div class="row">
            <button class="btn-second" id="myPropBtn">Upload Proposal</button>
        </div>
        <div class="row">
            <button class="btn-second" id="mypmmBtn">Upload Pengumuman</button>
        </div>
    </div>
    <div class="col p-2" style="align-items: flex-end;">
        <img src="{% static 'img/masjid.jpg' %}" style="width: 80%;" class="image" alt="image">
    </div>
</section>

{% include 'myapp/snippet/modal-doc.html' %}
{% include 'myapp/snippet/modal-prop.html' %}
{% include 'myapp/snippet/modal-pmm.html' %}
{% endblock content %}

myapp/templates/myapp/pengajuan.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{{page}}
{% endblock title %}

{% block header %}
{% endblock header %}

{% block content %}
<section class="section">
    <h1 class="title p-2">Pengajuan <br> Bantuan</h1>  
    
    <div class="pengajuan p-2">        
            {% for eachdata in page_obj %} 
            <a href="{% url 'myapp:item' eachdata.id %}" class="row">
                <img src="{% static 'img/dummy.jpg' %}" class="image" alt="image">
                <div class="col">
                    <div class="title">{{eachdata.prop.filename}}</div>
                    <div class="desc">
                        {{eachdata.prop.description}}
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga commodi nam voluptas nulla laboriosam quia voluptatem, autem distinctio, repellat doloribus laborum qui ipsum veritatis eaque, labore aliquam modi nihil porro.
                    </div>                    
                    <button class="btn-light">
                        SELANJUTNYA
                        <i class="fa-solid fa-arrow-right-long"></i>
                    </button>
                </div>
            </a>
            {% empty %}
            <h2>Belum Ada Proposal</h2>  
            {% endfor %}        
    </div>
    <div class="pagination p-2">
        <span class="step-links p-1">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
    
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</section>
{% endblock content %}

myapp/templates/myapp/snippet/login-modal.html
{% load static %}
<style>
    /* login-modal */
/* The login-modal (background) */
.login-modal {
    display: none; /* Hidden by default */
    position: fixed; /* Stay in place */
    z-index: 1; /* Sit on top */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /*Full height*/
    overflow: auto; /* Enable scroll if needed */
    background-color: rgb(0,0,0); /* Fallback color */
    background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
  }
  
  /* login-modal Content/Box */
  .login-modal-content {
    background-color: #fefefe;
    margin: 5% auto; /* 15% from the top and centered */
    padding: 20px;
    border: 1px solid #888;
    width: 50%; /* Could be more or less, depending on screen size */
    height: 80%;
  }
  .login-modal-content .title{
      display: flex;
      align-items: center;
      justify-content: center;
      font-size: 2em;
      font-weight: 700;
      flex-direction: column;
      margin-top: 40px;
  }
  .login-modal-content .form-input{
      width: auto;
  }
  
  /* The Close Button */
  .close {
    color: #aaa;
    float: right;
    font-size: 28px;
    font-weight: bold;
  }
  
  .close:hover,
  .close:focus {
    color: black;
    text-decoration: none;
    cursor: pointer;
  }
/* end of login-modal */
</style>

<!-- The login-modal -->
<div id="mylogin-modal" class="login-modal">

  <!-- login-modal content -->
  <div class="login-modal-content">
    <span class="close">&times;</span>
    <div class="title">
        LOGIN
        <br>
        <i class="fas fa-user-circle"></i>
    </div>
    <form action="{% url 'myapp:login' %}" method="post" class="form col p-2" style="margin-top:80px;">
      {% csrf_token %}
        <div class="form-input">            
            <input type="text" id="username" name="username" placeholder="Nama Pengguna">
        </div>
        <div class="form-input pass">            
            <input type="password" id="password" name="password" placeholder="Sandi">
            <label for="password">
                <i id="labelpass" class="fa-solid fa-eye"></i>
            </label>
        </div>        
        <div class="form-btn">
            <button type="submit" style="width: 100%; margin-top: 60px;" class="btn-black">
                Masuk                
            </button>
        </div>
    </form>
    
  </div>

</div>
<script>
    // Get the login-modal
var login = document.getElementById("mylogin-modal");

// Get the button that opens the login-modal
var btn = document.getElementById("myBtn");

// Get the <span> element that closes the login-modal
var span = document.getElementsByClassName("close")[0];

// When the user clicks on the button, open the login-modal
btn.onclick = function() {
  login.style.display = "block";
}

// When the user clicks on <span> (x), close the login-modal
span.onclick = function() {
  login.style.display = "none";
}

// When the user clicks anywhere outside of the login-modal, close it
window.onclick = function(event) {
  if (event.target == login) {
    login.style.display = "none";
  }
}

var eye = document.getElementById('labelpass');
var pass = document.getElementById('password');
eye.onclick = function() {
    if(pass.type === "password"){
        pass.type = "text";
        eye.className = "fa-solid fa-eye-slash";
    }
    else{
        pass.type = "password";
        eye.className ="fa-solid fa-eye";
    }
}
</script>

myapp/templates/myapp/snippet/modal-doc.html
{% load static %}
<style>
    /* modalDoc */
/* The ModalDoc (background) */
.modalDoc {
    display: none; /* Hidden by default */
    position: fixed; /* Stay in place */
    z-index: 1; /* Sit on top */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /* Full height */
    overflow: auto; /* Enable scroll if needed */
    background-color: rgb(0,0,0); /* Fallback color */
    background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
  }
  
  /* ModalDoc Content/Box */
  .modalDoc-content {
    background-color: #fefefe;
    margin: 5% auto; /* 15% from the top and centered */
    padding: 20px;
    border: 1px solid #888;
    width: 60%; /* Could be more or less, depending on screen size */
  }
  .modalDoc-content .title{
      display: flex;
      align-items: center;
      justify-content: center;
      font-size: 2em;
      font-weight: 700;
      flex-direction: column;
      margin-top: 40px;
  }
  .modalDoc-content .form-input{
      width: auto;
  }
  .modalDoc-content .form-group{
      display: none;
  }
  .upload{
      cursor: pointer;
      display: flex;
      flex-direction: column;
  }
  .center{
      text-align: center;
  }
  /* The CloseDoc Button */
  .closeDoc {
    color: #aaa;
    float: right;
    font-size: 28px;
    font-weight: bold;
  }
  
  .closeDoc:hover,
  .closeDoc:focus {
    color: black;
    text-decoration: none;
    cursor: pointer;
  }
/* end of modalDoc */
</style>

<!-- The ModalDoc -->
<div id="myModalDoc" class="modalDoc">

  <!-- ModalDoc content -->
  <div class="modalDoc-content">
    <span class="closeDoc">&times;</span>
    
    <div class="title">
        Upload Dokumentasi
    </div>
    <form method="POST" enctype="multipart/form-data" action="{% url 'myapp:upload_doc' %}" class="form col p-2" style="margin-top:20px;">
      {% csrf_token %}
        <label for="upload-photo" class="upload center" style="margin: 0px;">
            Tambah Gambar:
              <img 
                  id="output"
                  src="{% static 'img/dummy.jpg' %}"                   
                  style="width: 200px; height: 200px; margin:auto" 
                  alt=""
              >                                          
          </label>
          <div class="form-group">
            <!-- <label for="upload-photo"></label>                            -->
              <input type="file" name="picture" id="upload-photo" onchange="loadFile(event)" accept="image/*" class="">                    
          </div>               
        <div class="form-btn">
            <button type="submit" style="width: 100%; margin-top: 60px;" class="btn-black">
                Upload                
            </button>
        </div>
    </form>
  </div>

</div>
<script>
    // Get the modalDoc
var modalDoc = document.getElementById("myModalDoc");

// Get the button that opens the modalDoc
var btn = document.getElementById("modalDoc-btn");

// Get the <span> element that closeDocs the modalDoc
var span = document.getElementsByClassName("closeDoc")[0];

// When the user clicks on the button, open the modalDoc
btn.onclick = function() {
  modalDoc.style.display = "block";
}

// When the user clicks on <span> (x), closeDoc the modalDoc
span.onclick = function() {
  modalDoc.style.display = "none";
}

// When the user clicks anywhere outside of the modalDoc, closeDoc it
window.onclick = function(event) {
  if (event.target == modalDoc) {
    modalDoc.style.display = "none";
  }
}
</script>

myapp/templates/myapp/snippet/modal-pmm.html
{% load static %}
<style>
    /* pmm-modal */
/* The pmm-modal (background) */
.pmm-modal {
    display: none; /* Hidden by default */
    position: fixed; /* Stay in place */
    z-index: 1; /* Sit on top */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /*Full height*/
    overflow: auto; /* Enable scroll if needed */
    background-color: rgb(0,0,0); /* Fallback color */
    background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
  }
  
  /* pmm-modal Content/Box */
  .pmm-modal-content {
    background-color: #fefefe;
    margin: 5% auto; /* 15% from the top and centered */
    padding: 20px;
    border: 1px solid #888;
    width: 50%; /* Could be more or less, depending on screen size */
    height: 80%;
  }
  .pmm-modal-content .title{
      display: flex;
      align-items: center;
      justify-content: center;
      font-size: 2em;
      font-weight: 700;
      flex-direction: column;
      margin-top: 40px;
  }
  .pmm-modal-content .form-input{
      width: auto;
  }
  
  /* The Closepmm Button */
  .closepmm {
    color: #aaa;
    float: right;
    font-size: 28px;
    font-weight: bold;
  }
  
  .closepmm:hover,
  .closepmm:focus {
    color: black;
    text-decoration: none;
    cursor: pointer;
  }
/* end of pmm-modal */
</style>

<!-- The pmm-modal -->
<div id="mypmm-modal" class="pmm-modal">

  <!-- pmm-modal content -->
  <div class="pmm-modal-content">
    <span class="closepmm">&times;</span>
    <div class="title">
        Upload Pengumuman
    </div>
    <form method="POST" enctype="multipart/form-data" action="{% url 'myapp:upload_umum' %}" class="form col p-2" style="margin-top:20px;">               
      {% csrf_token %}
        <div class="form-input">            
            <input type="text" id="namaMasjid" name="namaMasjid" placeholder="Nama Masjid">
        </div>
        <div class="form-input">            
            <input type="text" id="tgl" name="tgl" placeholder="Tanggal">
        </div>
        <div class="form-input">            
            <input type="text" id="masjidketerangan" name="masjidketerangan" placeholder="Keterangan">
        </div>
        <div class="form-btn">
            <button type="submit" style="width: 100%; margin-top: 60px;" class="btn-black">
                Upload                
            </button>
        </div>
    </form>
    
  </div>

</div>
<script>
    // Get the pmm-modal
var pmm = document.getElementById("mypmm-modal");

// Get the button that opens the pmm-modal
var btn = document.getElementById("mypmmBtn");

// Get the <span> element that closepmms the pmm-modal
var span = document.getElementsByClassName("closepmm")[0];

// When the user clicks on the button, open the pmm-modal
btn.onclick = function() {
  pmm.style.display = "block";
}

// When the user clicks on <span> (x), closepmm the pmm-modal
span.onclick = function() {
  pmm.style.display = "none";
}

// When the user clicks anywhere outside of the pmm-modal, closepmm it
window.onclick = function(event) {
  if (event.target == pmm) {
    pmm.style.display = "none";
  }
}
</script>

myapp/templates/myapp/snippet/modal-prop.html
{% load static %}
<style>
    /* prop-modal */
/* The prop-modal (background) */
.prop-modal {
    display: none; /* Hidden by default */
    position: fixed; /* Stay in place */
    z-index: 1; /* Sit on top */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /*Full height*/
    overflow: auto; /* Enable scroll if needed */
    background-color: rgb(0,0,0); /* Fallback color */
    background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
  }
  
  /* prop-modal Content/Box */
  .prop-modal-content {
    background-color: #fefefe;
    margin: 5% auto; /* 15% from the top and centered */
    padding: 20px;
    border: 1px solid #888;
    width: 50%; /* Could be more or less, depending on screen size */
    height: 80%;
  }
  .prop-modal-content .title{
      display: flex;
      align-items: center;
      justify-content: center;
      font-size: 2em;
      font-weight: 700;
      flex-direction: column;
      margin-top: 40px;
  }
  .prop-modal-content .form-input{
      width: auto;
  }
  
  /* The CloseProp Button */
  .closeProp {
    color: #aaa;
    float: right;
    font-size: 28px;
    font-weight: bold;
  }
  
  .closeProp:hover,
  .closeProp:focus {
    color: black;
    text-decoration: none;
    cursor: pointer;
  }
/* end of prop-modal */
</style>

<!-- The prop-modal -->
<div id="myprop-modal" class="prop-modal">

  <!-- prop-modal content -->
  <div class="prop-modal-content">
    <span class="closeProp">&times;</span>
    <div class="title">
        Upload Proposal
    </div>
    <form method="POST" enctype="multipart/form-data" action="{% url 'myapp:upload_prop' %}" class="form col p-2" style="margin-top:20px;">
      {% csrf_token %}
        <div class="form-input">            
            <label for="berkas">Upload file</label>
            <input type="file" id="berkas" name="berkas">            
        </div>        
        <div class="form-input">            
            <input type="text" id="judul" name="judul" placeholder="Judul">
        </div>
        <div class="form-input">            
            <input type="text" id="keterangan" name="keterangan" placeholder="Keterangan">
        </div>
        <div class="form-btn">
            <button type="submit" style="width: 100%; margin-top: 60px;" class="btn-black">
                Upload                
            </button>
        </div>
    </form>
    
  </div>

</div>
<script>
    // Get the prop-modal
var prop = document.getElementById("myprop-modal");

// Get the button that opens the prop-modal
var btn = document.getElementById("myPropBtn");

// Get the <span> element that closeProps the prop-modal
var span = document.getElementsByClassName("closeProp")[0];

// When the user clicks on the button, open the prop-modal
btn.onclick = function() {
  prop.style.display = "block";
}

// When the user clicks on <span> (x), closeProp the prop-modal
span.onclick = function() {
  prop.style.display = "none";
}

// When the user clicks anywhere outside of the prop-modal, closeProp it
window.onclick = function(event) {
  if (event.target == prop) {
    prop.style.display = "none";
  }
}
</script>

templates/snippet/footer.html
{% load static %}
<footer class="footer col">    
    <div class="row">
        <!-- 1st col -->
        <div class="col p-2">
            <a href="{% url 'myapp:index' %}" class="logo">
                <img src="{% static 'img/Logo.svg' %}" alt="logo">
            </a>
        </div>
        <!-- 2nd col -->
        <ul class="col p-2">
            <li class="footer-list">
                <a href="{% url 'myapp:index' %}">Beranda</a>
            </li>
            <li class="footer-list">
                <a href="{% url 'myapp:dokumentasi' %}">Dokumentasi</a>
            </li>
            <li class="footer-list">
                <a href="{% url 'myapp:pengajuan' %}">Pengajuan Bantuan</a>
            </li>
            <li class="footer-list">
                <a href="{% url 'myapp:pengumuman' %}">Pengumuman</a>
            </li>
            <li class="footer-list">
                <a href="{% url 'myapp:contact' %}">Hubungi</a>
            </li>
        </ul>
        <!-- 3rd col -->
        <ul class="col p-2">
            <li class="footer-list">
                Kontak
            </li>
            <li class="footer-list">
                <i class="fas fa-map-marker-alt"></i> 
                Lingke, Syiah Kuala
            </li>
            <li class="footer-list">
                <i class="fa-solid fa-phone"></i>
                0813-6190-6789
            </li>            
            <li class="footer-list">
                <i class="fas fa-envelope"></i>
                hifomas@gmail.com
            </li>            
        </ul>
        <!-- 4th col -->
        <div class="col p-2">
            <div class="sosmed">
                Social Media
            </div>
            <div class="icon-sosmed row">
                <a href="#" class="col flink">
                    <i class="fab fa-facebook-f"></i>
                </a>
                <a href="#" class="col flink">
                    <i class="fab fa-twitter"></i>
                </a>
            </div>
        </div>
    </div>
    <div class="row copyright">
        &copy; 2022 All Right Reserved
    </div>    
</footer>

templates/snippet/navbar.html
{% load static %}
<nav class="navbar">
    <a href="{% url 'myapp:index' %}" class="logo">
        <img src="{% static 'img/Logo.svg' %}" alt="logo">
    </a>
    <button onclick="toggle()" class="btn-menu toggler">
        <i class="fa-solid fa-bars"></i>
    </button>
    <div class="navbar-collapse collapse" id="collapsed">
        <ul class="list-nav">
            <li class="navlink">
                <a href="{% url 'myapp:index' %}">BERANDA</a>
            </li>
            <li class="navlink">
                <a href="{% url 'myapp:dokumentasi' %}">DOKUMENTASI</a>
            </li>
            <li class="navlink">
                <a href="{% url 'myapp:pengajuan' %}">PENGAJUAN BANTUAN</a>
            </li>
            <li class="navlink">
                <a href="{% url 'myapp:pengumuman' %}">PENGUMUMAN</a>
            </li>
            <li class="navlink">
                <a href="{% url 'myapp:contact' %}">HUBUNGI</a>
            </li>
            {% if user.is_authenticated %}
            <li class="navlink">
                <a href="{% url 'myapp:menu' %}">Admin
                    <i class="fas fa-user-circle"></i>
                </a>
            </li>
            <li class="navlink">
                <a href="{% url 'myapp:logout' %}">LOGOUT
                    <i class="fa-solid fa-right-from-bracket"></i>
                </a>
            </li>
            {% else %}
            <li class="navlink">
                <a href="#" id="myBtn">LOGIN
                    <i class="fas fa-user-circle"></i>
                </a>
            </li>
            {% endif %}
        </ul>
    </div>
    {% include 'myapp/snippet/login-modal.html' %}
</nav>
<script>
    var button = document.getElementsByClassName('toggler');
  for (var i = 0; i < button.length; i++) {
    button[i].addEventListener('click', function () {
      var content = document.getElementById('collapsed');
      if (content.style.maxHeight) {
        // content.style.marginTop = '0px';
        content.style.maxHeight = null;
      } else {
        content.style.maxHeight = "320px";
        // content.style.marginTop = '20px';
      }
    });
  }
</script>

templates/snippet/script.html
{% load static %}
<script src="https://kit.fontawesome.com/8a82831e73.js" crossorigin="anonymous"></script>
<script src="{% static 'js/script.js' %}"></script>